name: Check
on:
  pull_request:
    branches: [ master, development ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: pnpm install

      - name: Check build
        run: pnpm build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
      - uses: pnpm/action-setup@v4
      - name: Install modules
        run: pnpm install

      - name: Run tests
        run: pnpm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
      - uses: pnpm/action-setup@v4

      - name: Install modules
        run: pnpm install

      - name: Eslint
        run: pnpm lint
